# Проверочное задание. Типы и структуры данных. Students

In [1]:
# Импортируй библиотеку pandas
import pandas as pd

In [ ]:
# Примонтируй Google Drive.
# В процессе выполнения кода этой ячейки перейди по длинной ссылке, скопируй код, вставь его
# в поле ввода и нажми <Enter>. Твой личный Google-диск "примонтируется", его папки
# станут видны в разделе файловой структуры слева.
from google.colab import drive
drive.mount('/content/drive')

In [3]:
# Размести на Google Drive файл students-mat.csv из материалов к заданию и загрузи его в dataframe
# Описание датасета: https://www.kaggle.com/uciml/student-alcohol-consumption

student = pd.read_csv('/content/drive/MyDrive/mydata/student-mat.csv')

In [4]:
# Выведи верхние строки датасета
student.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [5]:
# Выведи описательные статистики
student.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000
mean,16.696203,2.749367,2.521519,1.448101,2.035443,0.334177,3.944304,3.235443,3.108861,1.481013,2.291139,3.554430,5.708861,10.908861,10.713924,10.415190
std,1.276043,1.094735,1.088201,0.697505,0.839240,0.743651,0.896659,0.998862,1.113278,0.890741,1.287897,1.390303,8.003096,3.319195,3.761505,4.581443
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000,8.000000,9.000000,8.000000
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000,11.000000,11.000000,11.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000,13.000000,13.000000,14.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000,19.000000,19.000000,20.000000

In [7]:
# Оставь в датафрейме только признаки из этого списка:
cols = ['sex', 'age', 'romantic', 'freetime', 'studytime', 'paid', 'goout', 'G3']
student = student[cols]
print(student)

    sex  age romantic  freetime  studytime paid  goout  G3
0     F   18       no         3          2   no      4   6
1     F   17       no         3          2   no      3   6
2     F   15       no         3          2  yes      2  10
3     F   15      yes         2          3  yes      2  15
4     F   16       no         3          2  yes      2  10
..   ..  ...      ...       ...        ...  ...    ...  ..
390   M   20       no         5          2  yes      4   9
391   M   17       no         4          1   no      5  16
392   M   21       no         5          1   no      3   7
393   M   18       no         4          1   no      1  10
394   M   19       no         2          1   no      3   9

[395 rows x 8 columns]

In [11]:
#Средняя итоговая оценка у тех, кто берет дополнительные платные занятия, и у тех, кто нет.
print(student[student.paid == 'yes'].G3.mean())
print(student[student.paid == 'no'].G3.mean())

10.922651933701658
9.985981308411215

In [12]:
# Получи срез [3:6,'G3']
student.loc[3:6, 'G3']

3    15
4    10
5    15
6    11
Name: G3, dtype: int64

In [13]:
# Выведи на печать число женщин и мужчин
print(f"Женщин: {len(student[student.sex == 'F'])}")
print(f"Мужчин: {len(student[student.sex == 'M'])}")

Женщин: 208
Мужчин: 187

In [14]:
# Выведи число мужчин, имеющих романтические отношения. Используй логический оператор '&'.
len(student[(student.sex == 'M') & (student.romantic == 'yes')])

53

In [15]:
# Выведи медианное свободное время после школы у женщин
# Мы не можем брать среднее потому что эта переменная - не непрерывная, а порядковая категориальная переменная.
student[student.sex == 'F']['freetime'].median()

3.0

In [16]:
# Средний возраст женщин .loc()
student.loc[student.sex == 'F', 'age'].mean()

16.73076923076923

In [17]:
# Средний возраст мужчин, по-другому
student[student.sex == 'M'].age.mean()

16.657754010695186

###